# Site settings
title: Kwonyezy
email: kwonyezy@naver.com
description: >-
  Java developer
url: "https://kwonyezy.github.io"
baseurl: "/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: jekyll-theme-satellite
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

exclude: [
  'Gemfile', 
  'Gemfile.lock', 
  'node_modules', 
  'gray.gemspec',
  'Gulpfife.js', 
  'package.json',
  'package-lock.json',
  'LICENSE.txt',
  'README.md',
  'yarn.lock',
  '.gitignore'
]

paginate: 20
paginate_path: /page/:num
locale: EN

# Social networks
facebookurl: ''
twitterurl: ''
youtubeurl: ''
stackoverflowurl: ''
githuburl: ''
instagramurl: ''

# For analytics
idanalitycs: ''

# Language site
language: ''

# Google verification
googleverify: ''

# Email formspree
emailform: email@email.com

# Disqus 
disqus_user: https-kwonyezy-github-io
disqus_url: disqus.com/by/disqus_ed2tD4zj4o
disqus_id: kwonyezy

# About me
aboutme: kwonyezy@gmail.com
aboutmeimg: https://github.com/kwonyezy/kwonyezy.github.io/blob/master/_posts/pictures/img.jpeg?raw=true
