title: Portfolio
description: "My development blog and portfolio"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: kwonyezy@naver.com
github_username: kwonyezy

# External API
giscus_repo: "kwonyezy/kwonyezy.github.io"
giscus_repoId: "R_kgDOJ6fqWg"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOJ6fqWs4Cc7p7"

baseurl: ""  # 루트 경로를 사용하므로 빈 문자열로 설정
url: "https://kwonyezy.github.io"

theme: jekyll-theme-satellite

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "2024-06-07"

kramdown:
  input: GFM
  hard_wrap: true
