<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kwonyezy
email: kwonyezy@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  Java developer
url: "https://kwonyezy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: jekyll-theme-satellite
permalink: /:title/
=======
title: example.com
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: example@gmail.com
github_username: github
twitter_username: twitter
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo: "byanko55/jekyll-theme-satellite"
giscus_repoId: "R_kgDOJ6fqWg"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOJ6fqWs4Cc7p7"
goatcounter_code: byanko77
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
>>>>>>> 3be12514486a013c3b80d25f574a680baeed8aaa
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
<<<<<<< HEAD
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: [
  'Gemfile', 
  'Gemfile.lock', 
  'node_modules', 
  'Gemfile',
  'gray.gemspec',
  'Gulpfile.js', 
  'package.json',
  'package-lock.json',
  'LICENSE.txt',
  'README.md',
  'yarn.lock',
  '.gitignore'
]

#number posts for paginate
paginate: 20
paginate_path: /page/:num
locale: EN

#new variables:

#social networks
facebookurl: ''
twitterurl: ''
youtubeurl: ''
stackoverflowurl: ''
githuburl: ''
instagramurl: ''

#for analytics
idanalitycs: ''

#language site
language: ''

#google verification
googleverify: ''

#email formspree
emailform: email@email.com

#disqus 
disqus_user: https-kwonyezy-github-io
disqus_url: disqus.com/by/disqus_ed2tD4zj4o
disqus_id: kwonyezy

#about-me
aboutme: kwonyezy@gmail.com
aboutmeimg: https://github.com/kwonyezy/kwonyezy.github.io/blob/master/_posts/pictures/img.jpeg?raw=true
=======
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
>>>>>>> 3be12514486a013c3b80d25f574a680baeed8aaa
